### ISSUE TITLE
Audio Pipeline

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#14]

**Comment by jbartonthomas** [comment]
Just a heads-up that in addition to test slowness caused by tensorflow feature extraction not currently using the gpu, I noticed that the `common_primitives` `filereaderprimitive` seems to be taking ~20 minutes on the full audio dataset (the slowness happens at some point after the actual wav conversion and file load). None of the file reader stuff happens in parallel so I imagine it will be as bad under eval conditions. I am going to try adapting an existing uncharted primitive for audio load to see if I can speed up load and get us more head room for the upcoming tests.
